### ISSUE TITLE
Populate the cool links page

### ISSUE THREAD

**Issue by shubhsboson** [IterRoboticsClub/app_for_club#11]
The idea is to show clickable websites , youtube channels , instagram accounts , twitter accounts to follow .
There should be sections for each on the page.

**Comment by Zeo-shark** [comment]
- Kindly check the Sourav#issue10 branch and let me know for any bug or updates.

-It also has basic push Notification in the main.dart file kindly check that also We will have to customize it according to our need

**Comment by shubhsboson** [comment]
Not sure if this topic is being worked on or will be in future or if people in this org are active, hence closing the issue.

**Comment by shubhsboson** [comment]
Not sure if this topic is being worked on or will be in future or if people in this org are active, hence closing the issue.
