### ISSUE TITLE
Google sign in leads to homepage even without a successful sign in.

### ISSUE THREAD

**Issue by shubhsboson** [IterRoboticsClub/app_for_club#9]
**Describe the bug**
Sign in google should actually show a snack bar or something if sign in is successful and then only navigate to homepage and show a sign in unsuccessful message if it was not and then do nothing.
Instead it navigates to homepage either way.

**To Reproduce**
1. Switch off mobile data
2. Clear your app data
3. Try sign in with google

**Expected behavior**
It should say "sign in successful" if it is and then only go to homepage otherwise say "sign-in error".

Skip button works fine.

**Comment by Zeo-shark** [comment]
#9
**Updates**
Had Updated in the **dev_Sourav** to another signIn methods but the same thing happened (When Offline GoogleSignIn success). Looked into resources but the same thing happened for all tutorials . MayBe a feature of google offline signIn . 
[Supporting link :)](https://support.google.com/mail/answer/1306849?hl=en#:~:text=Use%20Gmail%20offline,.google.com%20in%20Chrome.)

**Comment by shubhsboson** [comment]
This error occurs cause .whenComplete() { } is invoked with the signInMethod which is like a default in switch case example so sign or no signIn it returns and so calls nav push to homepage.
